
const orb=document.getElementById('orb'),orbButton=document.getElementById('orbButton'),orbLabel=document.getElementById('orbLabel'),orbSubtitle=document.getElementById('orbSubtitle'),wave=document.getElementById('wave'),particles=document.getElementById('particles'),promptInput=document.getElementById('promptInput'),micButton=document.getElementById('micButton'),demoResult=document.getElementById('demoResult'),navOrb=document.getElementById('navOrb');
const states=['idle','listening','thinking','done'];let currentState='idle',busyTimer=null;
function seedParticles(){particles.innerHTML='';for(let i=0;i<22;i++){const p=document.createElement('span');p.className='particle';p.style.left=`${10+((i*17)%80)}%`;p.style.top=`${10+((i*29)%80)}%`;p.style.opacity=(.25+(i%4)*.15).toString();p.style.animationDelay=`${(i%6)*120}ms`;particles.appendChild(p)}}seedParticles();
function setState(next){currentState=next;orb.className=`orb ${next}`;wave.classList.toggle('hidden',next!=='listening');particles.classList.toggle('hidden',next!=='thinking');const map={idle:['ONE','Tocca per iniziare'],listening:['ONE','Ti ascolto…'],thinking:['ONE','Sto lavorando per te…'],done:['✓','Fatto!']};orbLabel.textContent=map[next][0];orbSubtitle.textContent=map[next][1]}
function nextState(){clearTimeout(busyTimer);const i=states.indexOf(currentState),next=states[(i+1)%states.length];setState(next);if(next==='done')busyTimer=setTimeout(()=>setState('idle'),1700)}
orbButton.addEventListener('click',nextState);navOrb.addEventListener('click',()=>setState('listening'));micButton.addEventListener('click',()=>setState(currentState==='listening'?'thinking':'listening'));
promptInput.addEventListener('keydown',e=>{if(e.key==='Enter'){const v=promptInput.value.trim();if(!v){setState('listening');return}setState('thinking');demoResult.classList.add('hidden');clearTimeout(busyTimer);busyTimer=setTimeout(()=>{setState('done');demoResult.textContent=`Demo ONE: ho ricevuto “${v}”. Nella versione AI reale qui comparirà l'azione suggerita.`;demoResult.classList.remove('hidden');promptInput.value='';busyTimer=setTimeout(()=>setState('idle'),1700)},1200)}});
document.querySelectorAll('.quick').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.action;setState('thinking');demoResult.classList.add('hidden');clearTimeout(busyTimer);busyTimer=setTimeout(()=>{setState('done');demoResult.textContent=`${action}: demo acquisizione completata. Nella prossima versione collegheremo questa azione a fotocamera, file o AI.`;demoResult.classList.remove('hidden');busyTimer=setTimeout(()=>setState('idle'),1700)},900)}));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
