const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const SUPABASE_URL="https://frehflwcnghrmqpzbpno.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_SuYaTiqS5F9OifFyuadFEA_xkAqQujw";
const ONE_AI_ENDPOINT=`${SUPABASE_URL}/functions/v1/one-ai`;
const ONE_TRANSCRIBE_ENDPOINT=`${SUPABASE_URL}/functions/v1/one-transcribe`;
const LEGAL_VERSION="1.1-2026-08-29";
const TERMS_HTML=`<div class="legal-note"><strong>Versione Beta.</strong> Questi termini sono una base operativa per il prototipo e dovranno essere completati prima della distribuzione commerciale.</div>
<h3>1. Ambito e accettazione</h3><p>I presenti Termini disciplinano l'uso di ONE, attualmente disponibile in versione Beta. Utilizzando ONE accetti questi Termini.</p>
<h3>2. Natura del servizio</h3><p>ONE è un assistente software basato anche su sistemi di intelligenza artificiale. Può analizzare testo, immagini, documenti e audio, memorizzare informazioni e suggerire azioni.</p>
<h3>3. Versione Beta e accuratezza</h3><p>I risultati AI possono contenere errori, omissioni o informazioni non aggiornate. Devi verificare le informazioni prima di usarle per decisioni importanti.</p>
<h3>4. Nessuna consulenza professionale</h3><p>ONE non sostituisce professionisti qualificati e non deve essere usato come unica fonte per decisioni mediche, legali, fiscali, finanziarie o di sicurezza.</p>
<h3>5. Contenuti dell'utente</h3><p>Resti responsabile dei contenuti caricati e dichiari di avere i diritti e le autorizzazioni necessari per utilizzarli.</p>
<h3>6. Account e sincronizzazione</h3><p>Puoi usare alcune funzioni senza account. Se crei un account, attività e Recall possono essere sincronizzati sul backend ONE e associati al tuo identificativo utente.</p>
<h3>7. Elaborazione tramite fornitori</h3><p>Per fornire le funzionalità richieste, ONE può trasmettere i contenuti ai servizi tecnici necessari, inclusi fornitori cloud e di intelligenza artificiale.</p>
<h3>8. Azioni e conferme</h3><p>Le azioni suggerite devono essere verificate dall'utente. Operazioni irreversibili o verso terzi dovranno richiedere conferma esplicita.</p>
<h3>9. Uso consentito</h3><p>È vietato usare ONE per attività illecite, frodi, malware, violazioni della sicurezza o dei diritti altrui.</p>
<h3>10. Disponibilità</h3><p>Il servizio è fornito nello stato in cui si trova e può essere modificato, sospeso o interrotto durante lo sviluppo.</p>
<h3>11. Responsabilità</h3><p>Nella misura consentita dalla legge, l'utente resta responsabile dell'uso dei risultati e delle azioni eseguite tramite ONE.</p>
<h3>12. Modifiche</h3><p>I Termini possono essere aggiornati con l'evoluzione del prodotto; per modifiche rilevanti potrà essere richiesta una nuova accettazione.</p>`;
const PRIVACY_HTML=`<div class="legal-note"><strong>Informativa preliminare Beta.</strong> Prima del rilascio commerciale dovrà essere completata con titolare, contatti, basi giuridiche, conservazione e altri elementi richiesti dal GDPR.</div>
<h3>1. Dati trattati</h3><p>A seconda delle funzioni utilizzate, ONE può trattare testo, immagini, documenti, audio, dati dell'account, attività e metadati tecnici.</p>
<h3>2. Finalità</h3><p>I dati sono usati per fornire le funzioni richieste, generare risposte e azioni, sincronizzare Recall e attività, mantenere sicurezza e affidabilità.</p>
<h3>3. AI e fornitori</h3><p>Quando usi funzioni AI, i contenuti necessari vengono inviati dal frontend al backend ONE e quindi ai fornitori tecnici necessari all'elaborazione.</p>
<h3>4. Memoria locale e cloud</h3><p>Senza account ONE usa una cronologia locale nel browser. Con un account, attività e Recall possono essere sincronizzati su Supabase con regole di accesso che limitano ogni utente ai propri dati.</p>
<h3>5. Dati sensibili</h3><p>Evita di inviare dati altamente sensibili o dati di terzi quando non è necessario o non sei autorizzato a farlo.</p>
<h3>6. Conservazione e diritti</h3><p>Tempi di conservazione, contatti e modalità per esercitare i diritti privacy saranno definiti nella versione commerciale definitiva.</p>
<h3>7. Sicurezza</h3><p>Le chiavi segrete dei servizi AI restano sul backend; il frontend usa esclusivamente credenziali pubblicabili e token di sessione personali.</p>`;

const orb=$("orb"),orbLabel=$("orbLabel"),orbSubtitle=$("orbSubtitle"),wave=$("wave"),particles=$("particles"),promptInput=$("promptInput"),micButton=$("micButton"),demoResult=$("demoResult"),navOrb=$("navOrb");
let state="idle",timer=null,recorder=null,chunks=[],stream=null,toastTimer=null,authMode="login",session=loadSession(),selectedSiteId=null,sitesCache=[];
let walkthrough={siteId:null,photos:[],draft:null,startedAt:null},walkthroughRecorder=null,walkthroughStream=null,walkthroughChunks=[];
const MAX_WALKTHROUGH_PHOTOS=6;
const WORKSPACE_ACTION_KINDS=new Set(["create_issue","create_activity","create_daily_report","update_site_progress"]);
const EXAMPLE_PACKS={
  residential:{icon:"⌂",name:"Cantiere residenziale",description:"Una villetta in costruzione con avanzamento, attività, criticità e giornale lavori.",site:{name:"Villa Aurora · Demo",client:"Famiglia Rossi",address:"Via dei Tigli 18 · Milano",progress:35,notes:"Pacchetto dimostrativo ONE · Cantiere residenziale"},activities:[{title:"Getto solaio piano primo",notes:"Getto completato e maturazione in corso."},{title:"Consegna laterizi",notes:"Materiale ricevuto e verificato in area deposito."}],issues:[{title:"Verifica quota vano scala",details:"Controllare la quota prima della posa del primo gradino.",priority:"Alta",dueDays:1},{title:"Confermare colore infissi",details:"Attesa conferma definitiva del cliente.",priority:"Media",dueDays:3}],report:{summary:"Struttura del piano primo completata",workers:7,hours:56,works:"Getto solaio, controllo armature e ricezione laterizi.",blockers:"In attesa della conferma sul colore degli infissi."}},
  office:{icon:"▦",name:"Ristrutturazione ufficio",description:"Una commessa interna con impianti, finiture, consegne e una criticità aperta.",site:{name:"Uffici Polaris · Demo",client:"Polaris S.r.l.",address:"Viale Europa 42 · Bologna",progress:62,notes:"Pacchetto dimostrativo ONE · Ristrutturazione ufficio"},activities:[{title:"Posa pareti vetrate",notes:"Completata l'ala nord; resta la sala riunioni."},{title:"Collaudo rete dati",notes:"Testate 38 prese su 42."}],issues:[{title:"Ritardo corpi illuminanti",details:"Il fornitore ha spostato la consegna di quattro giorni.",priority:"Alta",dueDays:2}],report:{summary:"Finiture e impianti in avanzamento",workers:5,hours:40,works:"Pareti vetrate, cablaggio dati e preparazione controsoffitti.",blockers:"Consegna corpi illuminanti da ripianificare."}}
};

const defaultActivities=[
{id:"demo1",icon:"▤",title:"Fattura ACME.pdf",detail:"Esempio attività ONE",time:"Demo",type:"document",demo:true},
{id:"demo2",icon:"⌂",title:"Ristorante salvato",detail:"Esempio Recall",time:"Demo",type:"place",demo:true},
{id:"demo3",icon:"✈",title:"Viaggio",detail:"Esempio monitoraggio",time:"Demo",type:"travel",demo:true}
];

function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add("hidden"),2600)}
function setState(s){state=s;orb.className="orb "+s;wave.classList.toggle("hidden",s!=="listening");particles.classList.toggle("hidden",s!=="thinking");const m={idle:["ONE","Tocca per iniziare"],listening:["ONE","Ti ascolto…"],thinking:["ONE","Sto pensando…"],done:["✓","Fatto!"]};orbLabel.textContent=m[s][0];orbSubtitle.textContent=m[s][1]}
function setAIStatus(ok,label){const e=$("aiStatus");e.classList.toggle("degraded",!ok);e.innerHTML=`<span></span> ${label}`}
function resultTarget(){return selectedSiteId&&$("siteView")?.classList.contains("active-view")?$("siteAiResult"):demoResult}
function show(message,isError=false){const target=resultTarget();target.innerHTML="";const p=document.createElement("div");p.textContent=message;target.appendChild(p);target.classList.toggle("error",isError);target.classList.remove("hidden")}
function loadSession(){try{return JSON.parse(localStorage.getItem("one_session")||"null")}catch{return null}}
function saveSession(s){session=s;if(s)localStorage.setItem("one_session",JSON.stringify(s));else localStorage.removeItem("one_session");updateAccountUI()}
async function ensureSession(){
  if(!session?.access_token)throw new Error("not_authenticated");
  if(!session.expires_at||session.expires_at>Date.now()/1000+60)return session;
  if(!session.refresh_token){saveSession(null);throw new Error("session_expired")}
  try{const refreshed=await authFetch("token?grant_type=refresh_token",{refresh_token:session.refresh_token});refreshed.expires_at=Math.floor(Date.now()/1000)+(refreshed.expires_in||3600);saveSession(refreshed);return refreshed}catch{saveSession(null);throw new Error("session_expired")}
}
function userId(){return session?.user?.id||null}
function getLocalActivities(){try{return JSON.parse(localStorage.getItem("one_activities"))||defaultActivities}catch{return defaultActivities}}
function saveLocalActivities(a){if(localStorage.one_history!=="off")localStorage.setItem("one_activities",JSON.stringify(a.slice(0,40)))}
async function cloudRequest(path,{method="GET",body}={}){
  const activeSession=await ensureSession();
  const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{"apikey":SUPABASE_ANON_KEY,"Authorization":`Bearer ${activeSession.access_token}`,"Content-Type":"application/json","Prefer":"return=representation"},body:body?JSON.stringify(body):undefined});
  if(r.status===401){saveSession(null);throw new Error("session_expired")}
  const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||`Errore cloud ${r.status}`);return data
}
async function syncFromCloud(){
  if(!session)return;
  try{
    $("recallCloudState").innerHTML='<span class="sync-spinner"></span> Sincronizzazione';
    const rows=await cloudRequest("one_activities?select=*&order=created_at.desc&limit=40");
    if(Array.isArray(rows)&&rows.length){
      const a=rows.map(x=>({id:x.id,icon:x.icon||"✦",title:x.title,detail:x.detail||"",time:new Date(x.created_at).toLocaleDateString("it-IT",{day:"2-digit",month:"2-digit"}),type:x.type||"activity",cloud:true}));
      saveLocalActivities(a);renderActivities();
    }
    $("recallCloudState").textContent="● Cloud sincronizzato";$("recallCloudState").classList.add("online")
  }catch(e){$("recallCloudState").textContent="○ Sync non disponibile";$("recallCloudState").classList.remove("online")}
}
async function addActivity(title,detail,icon="✦",type="ai",payload={}){
  const a=getLocalActivities();const local={id:Date.now().toString(),icon,title:title.slice(0,100),detail:detail.slice(0,180),time:"Ora",type};a.unshift(local);saveLocalActivities(a);renderActivities();
  if(session){
    try{await cloudRequest("one_activities",{method:"POST",body:{user_id:userId(),site_id:selectedSiteId||null,type,title:title.slice(0,180),detail:detail.slice(0,500),icon,payload}})}catch{}
  }
}
async function saveMemory(result,sourceType="ai",sourceName=""){
  const title=result?.memory_title||result?.summary||"Nuova memoria",summary=result?.memory_summary||result?.intent||result?.summary||"";
  if(!session){toast("Salvato nella cronologia locale. Accedi per Recall cloud.");return}
  try{await cloudRequest("one_memories",{method:"POST",body:{user_id:userId(),site_id:selectedSiteId||null,kind:result?.type||"note",title:title.slice(0,180),summary:summary.slice(0,700),source_type:sourceType,source_name:sourceName,payload:result?.extracted||{}}});toast("Salvato in Recall cloud");await loadCloudMemories()}catch{toast("Non riesco a salvare in Recall cloud")}
}
async function loadCloudMemories(){
  if(!session)return;
  try{
    const rows=await cloudRequest("one_memories?select=*&order=created_at.desc&limit=40");
    $("recallList").innerHTML=rows.length?rows.map(x=>`<button class="activity-card"><span class="a-icon">◌</span><span class="a-copy"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.summary||"")}</small></span><time>${new Date(x.created_at).toLocaleDateString("it-IT",{day:"2-digit",month:"2-digit"})}</time></button>`).join(""):`<div class="empty-state">Recall cloud è vuoto. Chiedi a ONE di analizzare qualcosa e salvalo.</div>`
  }catch{}
}
function renderActivities(){
  const a=getLocalActivities(), row=x=>`<button class="activity-card" data-activity="${x.id}"><span class="a-icon">${x.icon}</span><span class="a-copy"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.detail)}</small></span><time>${escapeHtml(x.time)}</time></button>`;
  $("recentCard").innerHTML=a.slice(0,3).map(x=>`<button class="recent-row" data-activity="${x.id}"><div class="recent-icon">${x.icon}</div><div class="recent-copy"><strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.detail)}</span></div><time>${escapeHtml(x.time)}</time></button>`).join("");
  $("allActivities").innerHTML=a.length?a.map(row).join(""):`<div class="empty-state">Nessuna attività.</div>`;
  if(!session)$("recallList").innerHTML=a.length?a.filter(x=>!x.demo).map(row).join("")||`<div class="empty-state">Recall locale è ancora vuoto.</div>`:`<div class="empty-state">Recall locale è ancora vuoto.</div>`;
  bindActivityClicks()
}
function bindActivityClicks(){$$("[data-activity]").forEach(b=>b.onclick=()=>{const a=getLocalActivities().find(x=>x.id===b.dataset.activity);if(a)openSheet("activity",a)})}

function showAIResult(result,source={type:"ai",name:""}){
  const target=resultTarget();target.innerHTML="";target.classList.remove("error");
  const title=document.createElement("strong");title.textContent=result?.summary||"Analisi completata";target.appendChild(title);
  if(result?.intent){const i=document.createElement("div");i.style.cssText="margin-top:8px;opacity:.75";i.textContent="ONE ha capito: "+result.intent;target.appendChild(i)}
  const wrap=document.createElement("div");wrap.style.cssText="display:flex;flex-wrap:wrap;gap:8px;margin-top:12px";
  const save=document.createElement("button");save.textContent=session?"Salva in Recall":"Ricorda";save.className="result-action";save.style.cssText="border:1px solid rgba(255,255,255,.15);background:rgba(255,255,255,.06);color:white;border-radius:999px;padding:9px 12px;font-size:12px";save.onclick=()=>saveMemory(result,source.type,source.name);wrap.appendChild(save);
  (result?.actions||[]).slice(0,3).forEach(action=>{const b=document.createElement("button");b.textContent=action.label||"Azione";b.style.cssText=save.style.cssText;b.onclick=()=>confirmAndExecuteAction(action,result);wrap.appendChild(b)});
  target.appendChild(wrap);target.classList.remove("hidden");
  addActivity(result?.summary||"Richiesta AI",result?.intent||"Elaborata da ONE","✦","ai",result?.extracted||{})
}
async function askONE(payload,source={type:"ai",name:""}){
  if(!session){show("Accedi a ONE per usare l'AI e proteggere il tuo spazio.",true);openAuth();return}
  setState("thinking");show("ONE sta analizzando…");
  try{
    const activeSession=await ensureSession();
    const r=await fetch(ONE_AI_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_ANON_KEY,"Authorization":`Bearer ${activeSession.access_token}`},body:JSON.stringify(payload)});
    const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.detail||data?.error||`Errore ${r.status}`);
    setAIStatus(true,"ONE AI attiva");setState("done");showAIResult(data.result||data,source);clearTimeout(timer);timer=setTimeout(()=>setState("idle"),1600)
  }catch(err){
    setState("idle");const msg=(err?.message||"").toLowerCase();
    if(msg.includes("credits")||msg.includes("billing")||msg.includes("quota")){setAIStatus(false,"AI in pausa");show("ONE è operativo, ma il motore AI è temporaneamente in pausa per il credito API.",true)}
    else{setAIStatus(false,"AI non disponibile");show("Non riesco a contattare il motore AI in questo momento.",true)}
  }
}
for(let i=0;i<22;i++){const p=document.createElement("span");p.className="particle";p.style.left=(10+((i*17)%80))+"%";p.style.top=(10+((i*29)%80))+"%";p.style.opacity=(.25+(i%4)*.15);p.style.animationDelay=((i%6)*120)+"ms";particles.appendChild(p)}

function showFile(f,label){const c=$("captureCard"),img=$("captureImage"),ico=$("captureIcon");c.classList.remove("hidden");$("captureTitle").textContent=label;$("captureMeta").textContent=`${f.name} · ${Math.max(1,Math.round(f.size/1024))} KB`;if(f.type.startsWith("image/")){img.src=URL.createObjectURL(f);img.classList.remove("hidden");ico.classList.add("hidden")}else{img.classList.add("hidden");ico.classList.remove("hidden")}addActivity(label,f.name,f.type.startsWith("image/")?"▧":"▤","capture")}
function readAsDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function readAsText(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsText(file)})}
function imageFileToDataURL(file,maxSide=1600,quality=.82){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>{const im=new Image();im.onload=()=>{let{width,height}=im;const sc=Math.min(1,maxSide/Math.max(width,height));width=Math.round(width*sc);height=Math.round(height*sc);const cv=document.createElement("canvas");cv.width=width;cv.height=height;cv.getContext("2d").drawImage(im,0,0,width,height);resolve(cv.toDataURL("image/jpeg",quality))};im.onerror=reject;im.src=rd.result};rd.onerror=reject;rd.readAsDataURL(file)})}
async function analyzeImageFile(file,label){showFile(file,label);try{await askONE({text:"Analizza ciò che ti sto mostrando e proponimi le azioni più utili.",image:await imageFileToDataURL(file)},{type:"image",name:file.name})}catch{show("Immagine acquisita, ma non riesco a prepararla per l'AI.",true)}}
async function analyzeDocument(file){
  showFile(file,"Documento");
  if(file.size>9_000_000){show("Per questa Beta i documenti devono essere inferiori a circa 9 MB.",true);return}
  try{
    if(file.type.startsWith("image/"))return analyzeImageFile(file,"Documento fotografato");
    if(file.type==="text/plain"||file.name.toLowerCase().endsWith(".txt"))return askONE({text:(await readAsText(file)).slice(0,18000)},{type:"document",name:file.name});
    const data=await readAsDataURL(file);
    await askONE({text:"Analizza questo documento. Riassumi i dati importanti e proponi azioni utili.",file:data,filename:file.name},{type:"document",name:file.name})
  }catch{show("Documento acquisito, ma l'analisi non è riuscita.",true)}
}
$("cameraBtn").onclick=()=>$("cameraInput").click();$("photoBtn").onclick=()=>$("photoInput").click();$("documentBtn").onclick=()=>$("documentInput").click();
$("cameraInput").onchange=e=>{const f=e.target.files?.[0];if(f)analyzeImageFile(f,"Foto dalla fotocamera")};
$("photoInput").onchange=e=>{const f=e.target.files?.[0];if(f)analyzeImageFile(f,"Foto selezionata")};
$("documentInput").onchange=e=>{const f=e.target.files?.[0];if(f)analyzeDocument(f)};
$("clearCapture").onclick=()=>{$("captureCard").classList.add("hidden");$("captureImage").src="";demoResult.classList.add("hidden")};

function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
async function requestTranscription(blob){const activeSession=await ensureSession(),r=await fetch(ONE_TRANSCRIBE_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_ANON_KEY,"Authorization":`Bearer ${activeSession.access_token}`},body:JSON.stringify({audio:await blobToDataURL(blob)})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||d?.error||"Trascrizione non riuscita");if(!d.text)throw new Error("Nessun testo riconosciuto");return String(d.text).trim()}
async function transcribeAudio(blob){
  if(!session){setState("idle");show("Accedi a ONE per trascrivere e proteggere la nota vocale.",true);openAuth();return}
  setState("thinking");show("Sto trascrivendo la tua voce…");
  try{
    const text=await requestTranscription(blob);
    addActivity("Nota vocale",text,"◉","audio");show(`Hai detto: “${text}”`);await askONE({text,...(selectedSiteId?{site_id:selectedSiteId}:{})},{type:"audio",name:"nota vocale"})
  }catch(e){setState("idle");show("La voce è stata acquisita, ma la trascrizione AI non è disponibile in questo momento.",true)}
}
async function toggleMic(){
  try{
    if(recorder&&recorder.state==="recording"){recorder.stop();return}
    if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){show("Registrazione vocale non disponibile in questo browser.",true);return}
    stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);
    recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
    recorder.onstop=async()=>{const blob=new Blob(chunks,{type:recorder.mimeType||"audio/webm"});stream.getTracks().forEach(t=>t.stop());await transcribeAudio(blob)};
    recorder.start();setState("listening");show("Registrazione in corso… Tocca di nuovo per fermare.")
  }catch{setState("idle");show("Non riesco ad accedere al microfono. Controlla il permesso del sito in Safari.",true)}
}
micButton.onclick=toggleMic;navOrb.onclick=toggleMic;$("orbButton").onclick=toggleMic;

$("askForm").onsubmit=async e=>{e.preventDefault();const v=promptInput.value.trim();if(!v)return;promptInput.value="";updateSend();await addActivity(v,"Richiesta inviata a ONE","✦","prompt");await askONE({text:v},{type:"text",name:"richiesta"})};
function updateSend(){const has=!!promptInput.value.trim();$("sendBtn").classList.toggle("hidden",!has);micButton.classList.toggle("hidden",has)}
promptInput.addEventListener("input",updateSend);

function localDateKey(value=new Date()){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return"";const pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function siteName(siteId){const site=sitesCache.find(item=>item.id===siteId);return site?`${site.job_number} · ${site.name}`:"Cantiere"}
function isClosedStatus(value=""){return ["risolto","risolta","chiusa","chiuso","completata","completato"].includes(String(value).trim().toLowerCase())}
function bindTodayItems(){$$("[data-today-site]").forEach(button=>button.onclick=()=>openSite(button.dataset.todaySite));$$('[data-today-action="reminders"]').forEach(button=>button.onclick=()=>openSheet("actions"))}
function showTodayLoggedOut(){const stateEl=$("todayState"),metrics=$("todayMetrics"),list=$("todayList");stateEl.classList.remove("hidden");metrics.classList.add("hidden");list.classList.add("hidden");stateEl.innerHTML=`<div class="today-login-copy"><strong>Il tuo briefing operativo</strong><span>Accedi per vedere priorità, scadenze e cantieri da aggiornare.</span></div><button id="todayLogin">Accedi</button>`;$("todayLogin").onclick=()=>openAuth()}
async function loadToday(){
  const stateEl=$("todayState"),metrics=$("todayMetrics"),list=$("todayList");if(!stateEl)return;
  if(!session){showTodayLoggedOut();return}
  stateEl.classList.remove("hidden");metrics.classList.add("hidden");list.classList.add("hidden");stateEl.innerHTML=`<div class="today-login-copy"><strong><span class="sync-spinner"></span> ONE sta preparando il briefing</strong><span>Controllo priorità, scadenze e aggiornamenti.</span></div>`;
  try{
    const today=localDateKey(),tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);tomorrow.setHours(23,59,59,999);
    const [sites,issues,reminders,reports]=await Promise.all([
      cloudRequest("sites?select=id,job_number,name,client,address,status,progress,updated_at&order=updated_at.desc"),
      cloudRequest("issues?select=id,site_id,title,priority,status,due_at,created_at&order=created_at.desc&limit=160"),
      cloudRequest("one_reminders?select=id,site_id,title,note,due_at,completed&completed=eq.false&order=created_at.desc&limit=60"),
      cloudRequest(`daily_reports?select=id,site_id,report_date&report_date=eq.${today}`)
    ]);
    sitesCache=Array.isArray(sites)?sites:[];const openIssues=(Array.isArray(issues)?issues:[]).filter(item=>!isClosedStatus(item.status));
    const urgent=openIssues.filter(item=>["critica","alta"].includes(String(item.priority||"").toLowerCase()));
    const overdue=openIssues.filter(item=>item.due_at&&new Date(item.due_at)<new Date());
    const dueReminders=(Array.isArray(reminders)?reminders:[]).filter(item=>item.due_at&&new Date(item.due_at)<=tomorrow);
    const reportedSites=new Set((Array.isArray(reports)?reports:[]).map(item=>item.site_id));
    const activeSites=sitesCache.filter(site=>!["chiuso","completato","archiviato"].includes(String(site.status||"").toLowerCase()));
    const missingReports=activeSites.filter(site=>!reportedSites.has(site.id));
    const items=[];
    [...overdue,...urgent.filter(item=>!overdue.some(x=>x.id===item.id))].slice(0,5).forEach(issue=>items.push({icon:issue.due_at&&new Date(issue.due_at)<new Date()?"⏱":"!",title:issue.title,detail:`${siteName(issue.site_id)} · ${issue.priority||"Priorità"}`,tag:issue.due_at&&new Date(issue.due_at)<new Date()?"SCADUTO":"URGENTE",siteId:issue.site_id}));
    dueReminders.slice(0,2).forEach(item=>items.push({icon:"◷",title:item.title,detail:item.due_at?new Date(item.due_at).toLocaleString("it-IT"):item.note||"Promemoria",tag:"PROMEMORIA",action:"reminders"}));
    missingReports.slice(0,2).forEach(site=>items.push({icon:"▤",title:`Aggiornamento ${site.job_number}`,detail:`${site.name} · report di oggi non presente`,tag:"DA AGGIORNARE",siteId:site.id}));
    stateEl.classList.add("hidden");metrics.classList.remove("hidden");list.classList.remove("hidden");
    metrics.innerHTML=`<div class="today-metric urgent"><strong>${urgent.length}</strong><span>priorità alte</span></div><div class="today-metric due"><strong>${overdue.length+dueReminders.length}</strong><span>scadenze</span></div><div class="today-metric"><strong>${missingReports.length}</strong><span>cantieri da aggiornare</span></div>`;
    list.innerHTML=items.length?items.map(item=>`<button class="today-item" ${item.siteId?`data-today-site="${item.siteId}"`:`data-today-action="${item.action}"`}><span>${item.icon}</span><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.detail)}</small></div><b>${item.tag}</b></button>`).join(""):`<div class="today-state card"><div class="today-login-copy"><strong>Nessuna urgenza rilevata</strong><span>ONE non vede scadenze o priorità critiche per oggi.</span></div><span style="color:#79e7c7">✓</span></div>`;
    bindTodayItems()
  }catch{stateEl.classList.remove("hidden");metrics.classList.add("hidden");list.classList.add("hidden");stateEl.innerHTML=`<div class="today-login-copy"><strong>Briefing non disponibile</strong><span>Controlla la connessione o aggiorna tra poco.</span></div><button id="retryToday">Riprova</button>`;$("retryToday").onclick=loadToday}
}

function siteStatusLabel(status=""){return status||"Da pianificare"}
function progressValue(value){return Math.min(100,Math.max(0,Number(value)||0))}
function siteCard(site){const progress=progressValue(site.progress);return `<button class="workspace-card" data-site="${site.id}"><div class="workspace-card-top"><span class="workspace-icon">⌂</span><span class="workspace-copy"><strong>${escapeHtml(site.job_number)} · ${escapeHtml(site.name)}</strong><small>${escapeHtml(site.client||site.address||"Cantiere")}</small></span><span class="chev">›</span></div><div class="progress-row"><span><i style="width:${progress}%"></i></span><b>${progress}%</b></div><div class="workspace-meta"><span>${escapeHtml(siteStatusLabel(site.status))}</span><span>Apri spazio</span></div></button>`}
async function loadWorkspaces(){
  const list=$("workspaceSites"),workspaceState=$("workspaceState");
  if(!session){workspaceState.textContent="Accedi per vedere i cantieri assegnati al tuo account.";list.innerHTML=`<button class="workspace-login" id="workspaceLogin">Accedi a ONE</button>`;$("workspaceLogin").onclick=()=>openAuth();return}
  workspaceState.textContent="Caricamento spazi…";list.innerHTML=`<div class="empty-state"><span class="sync-spinner"></span> Sincronizzazione</div>`;
  try{sitesCache=await cloudRequest("sites?select=id,job_number,name,client,address,status,progress,updated_at&order=updated_at.desc");workspaceState.textContent=`${sitesCache.length} ${sitesCache.length===1?"cantiere disponibile":"cantieri disponibili"}`;list.innerHTML=sitesCache.length?sitesCache.map(siteCard).join(""):`<div class="empty-state">Non hai ancora cantieri assegnati.</div>`;$$("[data-site]").forEach(button=>button.onclick=()=>openSite(button.dataset.site))}catch{workspaceState.textContent="Spazi non disponibili";list.innerHTML=`<div class="empty-state">Non riesco a caricare i cantieri. Verifica la sessione e riprova.</div>`}
}
async function openSite(siteId){
  const site=sitesCache.find(item=>item.id===siteId);if(!site)return;
  selectedSiteId=siteId;navigate("site",true);$("siteTitle").textContent=site.name;$("siteSubtitle").textContent=`${site.job_number}${site.client?` · ${site.client}`:""}`;$("siteProgress").textContent=`${progressValue(site.progress)}%`;$("siteStatus").textContent=siteStatusLabel(site.status);$("siteAddress").textContent=site.address||"Indirizzo non indicato";$("sitePulse").innerHTML=`<div class="empty-state"><span class="sync-spinner"></span> Aggiornamento del cantiere</div>`;
  try{
    const [issues,activities,reports,documents,members]=await Promise.all([
      cloudRequest(`issues?select=id,title,details,priority,status,due_at,created_at&site_id=eq.${encodeURIComponent(siteId)}&order=created_at.desc&limit=30`),
      cloudRequest(`activities?select=id,title,notes,created_at&site_id=eq.${encodeURIComponent(siteId)}&order=created_at.desc&limit=20`),
      cloudRequest(`daily_reports?select=id,report_date,summary,works,blockers,workers,hours&site_id=eq.${encodeURIComponent(siteId)}&order=report_date.desc&limit=10`),
      cloudRequest(`documents?select=id,file_name,category,created_at&site_id=eq.${encodeURIComponent(siteId)}&order=created_at.desc&limit=20`),
      cloudRequest(`site_members?select=id,role&site_id=eq.${encodeURIComponent(siteId)}`)
    ]);
    const openIssues=issues.filter(issue=>!["Risolto","Chiusa","Completata"].includes(issue.status));
    const urgent=openIssues.filter(issue=>["Critica","Alta"].includes(issue.priority));
    $("sitePulse").innerHTML=`<div class="pulse-grid"><div><strong>${openIssues.length}</strong><span>Problemi aperti</span></div><div><strong>${urgent.length}</strong><span>Priorità alte</span></div><div><strong>${members.length}</strong><span>Persone</span></div><div><strong>${documents.length}</strong><span>Documenti</span></div></div>`;
    $("siteIssues").innerHTML=openIssues.length?openIssues.slice(0,6).map(issue=>`<div class="site-row"><span class="priority-dot ${issue.priority==="Critica"?"critical":issue.priority==="Alta"?"high":""}"></span><div><strong>${escapeHtml(issue.title)}</strong><small>${escapeHtml(issue.priority)} · ${escapeHtml(issue.status)}</small></div></div>`).join(""):`<div class="empty-state compact">Nessun problema aperto.</div>`;
    const feed=[...activities.map(item=>({title:item.title,detail:item.notes||"Attività",date:item.created_at,icon:"✓"})),...reports.map(item=>({title:`Report ${new Date(item.report_date).toLocaleDateString("it-IT")}`,detail:item.summary||item.works||"Report giornaliero",date:item.report_date,icon:"▤"}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6);
    $("siteFeed").innerHTML=feed.length?feed.map(item=>`<div class="site-row"><span class="feed-icon">${item.icon}</span><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.detail)}</small></div></div>`).join(""):`<div class="empty-state compact">Nessun aggiornamento recente.</div>`;
  }catch{$("sitePulse").innerHTML=`<div class="empty-state">Dati del cantiere temporaneamente non disponibili.</div>`}
}

function walkthroughSite(){return sitesCache.find(site=>site.id===walkthrough.siteId)||null}
function showWalkthroughStatus(message,error=false){const el=$("walkthroughStatus");el.textContent=message;el.classList.remove("hidden");el.classList.toggle("error",error)}
function resetWalkthrough(siteId){walkthrough={siteId,photos:[],draft:null,startedAt:new Date().toISOString()};$("walkthroughNotes").value="";$("walkthroughCapture").classList.remove("hidden");$("walkthroughReview").classList.add("hidden");$("walkthroughReview").innerHTML="";$("walkthroughStatus").classList.add("hidden");renderWalkthroughPhotos()}
function startWalkthrough(){if(!session){openAuth();toast("Accedi per avviare il sopralluogo");return}const site=sitesCache.find(item=>item.id===selectedSiteId);if(!site){toast("Apri prima un cantiere");return}resetWalkthrough(site.id);$("walkthroughSiteName").textContent=`${site.job_number} · ${site.name}`;navigate("walkthrough",true)}
function renderWalkthroughPhotos(){const grid=$("walkthroughPhotos"),count=walkthrough.photos.length;$("walkthroughPhotoCount").textContent=`${count} di ${MAX_WALKTHROUGH_PHOTOS}`;grid.innerHTML=count?walkthrough.photos.map(photo=>`<div class="walkthrough-photo"><img src="${photo.dataUrl}" alt="${escapeHtml(photo.name)}"><button type="button" data-remove-walkthrough-photo="${photo.id}" aria-label="Rimuovi foto">×</button></div>`).join(""):`<button id="walkthroughEmptyPhotos" type="button" class="walkthrough-empty">Aggiungi fotografie utili a documentare lavorazioni e criticità</button>`;$$('[data-remove-walkthrough-photo]').forEach(button=>button.onclick=()=>{walkthrough.photos=walkthrough.photos.filter(photo=>photo.id!==button.dataset.removeWalkthroughPhoto);renderWalkthroughPhotos()});if($("walkthroughEmptyPhotos"))$("walkthroughEmptyPhotos").onclick=()=>$("walkthroughPhotoInput").click()}
async function addWalkthroughPhotos(fileList){const files=[...fileList].filter(file=>file.type.startsWith("image/")),available=MAX_WALKTHROUGH_PHOTOS-walkthrough.photos.length;if(!available){toast("Hai già aggiunto il massimo di 6 fotografie");return}showWalkthroughStatus("Preparazione delle fotografie…");for(const file of files.slice(0,available)){try{if(file.size>14_000_000)throw new Error("troppo grande");const dataUrl=await imageFileToDataURL(file,1600,.78);walkthrough.photos.push({id:`photo-${Date.now()}-${walkthrough.photos.length}`,name:file.name||"Foto sopralluogo",dataUrl})}catch{toast(`${file.name||"Una fotografia"} non è stata aggiunta`)}}renderWalkthroughPhotos();$("walkthroughStatus").classList.add("hidden");if(files.length>available)toast(`Aggiunte ${available} foto: il limite è ${MAX_WALKTHROUGH_PHOTOS}`)}
async function toggleWalkthroughVoice(){const button=$("walkthroughVoice");try{if(walkthroughRecorder?.state==="recording"){walkthroughRecorder.stop();return}if(!session){openAuth();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){showWalkthroughStatus("Registrazione vocale non disponibile in questo browser.",true);return}walkthroughStream=await navigator.mediaDevices.getUserMedia({audio:true});walkthroughChunks=[];walkthroughRecorder=new MediaRecorder(walkthroughStream);walkthroughRecorder.ondataavailable=event=>{if(event.data.size)walkthroughChunks.push(event.data)};walkthroughRecorder.onstop=async()=>{button.classList.remove("recording");button.querySelector("strong").textContent="Voce";walkthroughStream?.getTracks().forEach(track=>track.stop());showWalkthroughStatus("Trascrizione della nota vocale…");try{const blob=new Blob(walkthroughChunks,{type:walkthroughRecorder.mimeType||"audio/webm"}),text=await requestTranscription(blob),notes=$("walkthroughNotes");notes.value=`${notes.value}${notes.value?"\n\n":""}${text}`.slice(0,8000);showWalkthroughStatus("✓ Nota vocale aggiunta");setTimeout(()=>$("walkthroughStatus").classList.add("hidden"),1400)}catch(error){showWalkthroughStatus(error?.message||"Trascrizione non riuscita",true)}};walkthroughRecorder.start();button.classList.add("recording");button.querySelector("strong").textContent="Ferma";showWalkthroughStatus("Registrazione in corso… Tocca di nuovo per fermare.")}catch{button.classList.remove("recording");showWalkthroughStatus("Non riesco ad accedere al microfono. Controlla il permesso del browser.",true)}}
function cancelWalkthroughRecording(){const button=$("walkthroughVoice");if(walkthroughRecorder?.state==="recording"){walkthroughRecorder.onstop=()=>walkthroughStream?.getTracks().forEach(track=>track.stop());walkthroughRecorder.stop()}walkthroughStream?.getTracks().forEach(track=>track.stop());button.classList.remove("recording");button.querySelector("strong").textContent="Voce"}
async function analyzeWalkthrough(){const notes=$("walkthroughNotes").value.trim(),button=$("analyzeWalkthrough"),site=walkthroughSite();if(!site)return;if(!notes&&!walkthrough.photos.length){showWalkthroughStatus("Aggiungi almeno una nota o una fotografia.",true);return}button.disabled=true;showWalkthroughStatus(`ONE sta analizzando ${walkthrough.photos.length?`${walkthrough.photos.length} fotografie e gli appunti`:"gli appunti"}…`);try{const activeSession=await ensureSession(),response=await fetch(ONE_AI_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_ANON_KEY,"Authorization":`Bearer ${activeSession.access_token}`},body:JSON.stringify({mode:"walkthrough",text:notes||"Analizza le fotografie del sopralluogo e prepara il rapporto.",site_id:site.id,images:walkthrough.photos.map(photo=>photo.dataUrl)})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.detail||payload?.error||`Errore ${response.status}`);const result=payload.result||payload,draft=result.walkthrough;if(!draft)throw new Error("ONE non ha restituito una bozza di sopralluogo");walkthrough.draft=draft;renderWalkthroughReview(draft,result.summary)}catch(error){showWalkthroughStatus(error?.message||"Analisi del sopralluogo non riuscita",true);button.disabled=false}}
function reviewActivityCard(item,index){return `<article class="walkthrough-review-card"><label class="walkthrough-card-toggle"><input type="checkbox" name="activity_${index}_enabled" checked> Registra attività</label><label>Titolo<input name="activity_${index}_title" maxlength="180" value="${escapeHtml(item.title||"")}"></label><label>Note<textarea name="activity_${index}_notes" maxlength="1600">${escapeHtml(item.notes||"")}</textarea></label></article>`}
function reviewIssueCard(item,index){return `<article class="walkthrough-review-card"><label class="walkthrough-card-toggle"><input type="checkbox" name="issue_${index}_enabled" checked> Apri criticità</label><label>Titolo<input name="issue_${index}_title" maxlength="180" value="${escapeHtml(item.title||"")}"></label><label>Dettagli<textarea name="issue_${index}_details" maxlength="1600">${escapeHtml(item.details||"")}</textarea></label><div class="operation-grid"><label>Priorità<select name="issue_${index}_priority">${["Bassa","Media","Alta","Critica"].map(priority=>`<option ${priority===(item.priority||"Media")?"selected":""}>${priority}</option>`).join("")}</select></label><label>Scadenza<input name="issue_${index}_due_at" type="datetime-local" value="${dateTimeLocalValue(item.due_at)}"></label></div></article>`}
function renderWalkthroughReview(draft,summary=""){const site=walkthroughSite(),activities=Array.isArray(draft.activities)?draft.activities.slice(0,8):[],issues=Array.isArray(draft.issues)?draft.issues.slice(0,8):[];$("walkthroughCapture").classList.add("hidden");const review=$("walkthroughReview");review.classList.remove("hidden");review.innerHTML=`<div class="walkthrough-review-head"><span>BOZZA PRONTA</span><h2>Controlla prima di salvare</h2><p>${escapeHtml(summary||`ONE ha preparato il rapporto per ${site?.name||"il cantiere"}.`)}</p></div><form id="walkthroughReviewForm" class="walkthrough-review-form"><label>Data rapporto<input name="report_date" type="date" required value="${localDateKey()}"></label><label>Riepilogo<input name="summary" maxlength="500" value="${escapeHtml(draft.summary||"")}"></label><label>Lavorazioni<textarea name="works" maxlength="2400">${escapeHtml(draft.works||"")}</textarea></label><label>Blocchi e criticità<textarea name="blockers" maxlength="1600">${escapeHtml(draft.blockers||"")}</textarea></label><div class="walkthrough-review-grid"><label>Persone<input name="workers" type="number" min="0" step="1" value="${escapeHtml(draft.workers??"")}"></label><label>Ore totali<input name="hours" type="number" min="0" step="0.5" value="${escapeHtml(draft.hours??"")}"></label><label>Avanzamento %<input name="progress" type="number" min="0" max="100" step="1" placeholder="${progressValue(site?.progress)}" value="${escapeHtml(draft.suggested_progress??"")}"></label></div>${activities.length?`<div class="walkthrough-review-section">ATTIVITÀ RILEVATE · ${activities.length}</div>${activities.map(reviewActivityCard).join("")}`:""}${issues.length?`<div class="walkthrough-review-section">CRITICITÀ RILEVATE · ${issues.length}</div>${issues.map(reviewIssueCard).join("")}`:""}<div id="walkthroughSaveStatus" class="operation-status hidden"></div><button class="primary-btn" type="submit">Conferma e salva tutto</button><button id="editWalkthrough" class="walkthrough-secondary" type="button">Torna all'acquisizione</button><p class="walkthrough-save-note">Le fotografie sono usate per preparare questa bozza, ma non vengono archiviate nel cantiere in questa release.</p></form>`;$("editWalkthrough").onclick=()=>{$("walkthroughReview").classList.add("hidden");$("walkthroughCapture").classList.remove("hidden");$("analyzeWalkthrough").disabled=false};$("walkthroughReviewForm").onsubmit=saveWalkthrough}
async function saveWalkthrough(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),draft=walkthrough.draft||{},activities=(draft.activities||[]).slice(0,8).flatMap((_,index)=>data.get(`activity_${index}_enabled`)?[{title:String(data.get(`activity_${index}_title`)||"").trim(),notes:String(data.get(`activity_${index}_notes`)||"").trim()||null}]:[]).filter(item=>item.title),issues=(draft.issues||[]).slice(0,8).flatMap((_,index)=>data.get(`issue_${index}_enabled`)?[{title:String(data.get(`issue_${index}_title`)||"").trim(),details:String(data.get(`issue_${index}_details`)||"").trim()||null,priority:String(data.get(`issue_${index}_priority`)||"Media"),due_at:data.get(`issue_${index}_due_at`)?new Date(String(data.get(`issue_${index}_due_at`))).toISOString():null}]:[]).filter(item=>item.title),report={report_date:String(data.get("report_date")||localDateKey()),summary:String(data.get("summary")||"").trim()||null,works:String(data.get("works")||"").trim()||null,blockers:String(data.get("blockers")||"").trim()||null,workers:data.get("workers")===""?0:Number(data.get("workers")),hours:data.get("hours")===""?0:Number(data.get("hours"))},progress=data.get("progress")===""?null:progressValue(data.get("progress")),status=$("walkthroughSaveStatus"),submit=form.querySelector('[type="submit"]');status.classList.remove("hidden","error");status.textContent="Salvataggio atomico del sopralluogo…";submit.disabled=true;try{const saved=await cloudRequest("rpc/commit_site_walkthrough",{method:"POST",body:{p_site_id:walkthrough.siteId,p_report:report,p_activities:activities,p_issues:issues,p_progress:progress}}),site=walkthroughSite();if(site&&progress!==null)site.progress=progress;await logAction({kind:"site_walkthrough",label:"Sopralluogo completato",payload:{site_id:walkthrough.siteId,photos:walkthrough.photos.length,activities:activities.length,issues:issues.length,report_id:saved?.report_id||null}},"executed");await addActivity("Sopralluogo completato",`${siteName(walkthrough.siteId)} · ${activities.length} attività · ${issues.length} criticità`,"◎","site_walkthrough",{site_id:walkthrough.siteId});await loadToday();renderWalkthroughComplete(saved,activities.length,issues.length)}catch(error){status.textContent=error?.message||"Salvataggio non riuscito";status.classList.add("error");submit.disabled=false}}
function renderWalkthroughComplete(saved,activityCount,issueCount){const review=$("walkthroughReview");review.innerHTML=`<div class="walkthrough-complete"><span>✓</span><h2>Sopralluogo registrato</h2><p>Creato il giornale lavori con ${activityCount} attività e ${issueCount} criticità. Tutto è stato salvato in un'unica operazione.</p><button id="walkthroughOpenSite" class="primary-btn">Torna al cantiere</button></div>`;$("walkthroughOpenSite").onclick=()=>openSite(walkthrough.siteId)}

function navigate(name,preserveSite=false){const leavingWalkthrough=$("walkthroughView").classList.contains("active-view")&&!["walkthrough","site"].includes(name);if(leavingWalkthrough&&($("walkthroughNotes").value.trim()||walkthrough.photos.length)&&!confirm("Uscire dal sopralluogo? I dati non ancora confermati andranno persi."))return;if(leavingWalkthrough)cancelWalkthroughRecording();const map={home:"homeView",spaces:"spacesView",site:"siteView",walkthrough:"walkthroughView",activities:"activitiesView",recall:"recallView",search:"searchView",profile:"profileView"};if(!preserveSite&&!["site","walkthrough"].includes(name))selectedSiteId=null;$$(".view").forEach(v=>v.classList.remove("active-view"));$(map[name]||map.home).classList.add("active-view");$$(".bottom-nav>button:not(.nav-orb)").forEach(b=>b.classList.remove("active"));const nav={home:"navHome",spaces:"navSpaces",site:"navSpaces",walkthrough:"navSpaces",search:"navSearch",profile:"navProfile"};if(nav[name])$(nav[name]).classList.add("active");closeDrawer();window.scrollTo({top:0,behavior:"smooth"});if(name==="search")setTimeout(()=>$("searchInput").focus(),250);if(name==="recall"&&session)loadCloudMemories();if(name==="spaces")loadWorkspaces();if(name==="home")loadToday()}
$("navHome").onclick=()=>navigate("home");$("navSpaces").onclick=()=>navigate("spaces");$("navSearch").onclick=()=>navigate("search");$("navProfile").onclick=()=>navigate("profile");$$("[data-home]").forEach(b=>b.onclick=()=>navigate("home"));$("seeAll").onclick=()=>navigate("activities");$("memoryCard").onclick=()=>navigate("recall");$("profileBtn").onclick=()=>navigate("profile");$("siteBack").onclick=()=>navigate("spaces");
$("walkthroughStart").onclick=startWalkthrough;$("walkthroughVoice").onclick=toggleWalkthroughVoice;$("walkthroughCamera").onclick=()=>$("walkthroughCameraInput").click();$("walkthroughLibrary").onclick=()=>$("walkthroughPhotoInput").click();$("walkthroughCameraInput").onchange=async event=>{await addWalkthroughPhotos(event.target.files||[]);event.target.value=""};$("walkthroughPhotoInput").onchange=async event=>{await addWalkthroughPhotos(event.target.files||[]);event.target.value=""};$("analyzeWalkthrough").onclick=analyzeWalkthrough;$("discardWalkthrough").onclick=()=>{if(($("walkthroughNotes").value.trim()||walkthrough.photos.length)&&!confirm("Annullare il sopralluogo? Gli appunti e le fotografie non salvati andranno persi."))return;cancelWalkthroughRecording();openSite(walkthrough.siteId)};$("walkthroughBack").onclick=()=>{if(($("walkthroughNotes").value.trim()||walkthrough.photos.length||walkthrough.draft)&&!confirm("Uscire dal sopralluogo senza salvarlo?"))return;cancelWalkthroughRecording();openSite(walkthrough.siteId)};
$("siteAskForm").onsubmit=async e=>{e.preventDefault();const input=$("sitePromptInput"),value=input.value.trim();if(!value||!selectedSiteId)return;input.value="";await addActivity(value,"Richiesta sul cantiere","✦","site_prompt");await askONE({text:value,site_id:selectedSiteId},{type:"site",name:$("siteTitle").textContent})};
$$("[data-site-action]").forEach(button=>button.onclick=()=>openOperationReview({kind:button.dataset.siteAction,label:workspaceActionTitle(button.dataset.siteAction),payload:{site_id:selectedSiteId}},{summary:`Operazione per ${$("siteTitle").textContent}`}));
$("refreshToday").onclick=loadToday;$("todayLogin").onclick=()=>openAuth();
function openDrawer(){$("drawer").classList.add("open");$("drawer").setAttribute("aria-hidden","false");$("scrim").classList.remove("hidden")}
function closeDrawer(){$("drawer").classList.remove("open");$("drawer").setAttribute("aria-hidden","true");if(!$("sheet").classList.contains("open"))$("scrim").classList.add("hidden")}
$("menuBtn").onclick=openDrawer;$("drawerClose").onclick=closeDrawer;$("scrim").onclick=()=>{closeDrawer();closeSheet()};$$("[data-nav]").forEach(b=>b.onclick=()=>navigate(b.dataset.nav));

function openSheet(type,data={}){
  closeDrawer();const title=$("sheetTitle"),sub=$("sheetSubtitle"),body=$("sheetBody");
  const t={
    terms:()=>{title.textContent="Termini di utilizzo";sub.textContent="Versione 1.1 · 29 agosto 2026";body.innerHTML=TERMS_HTML},
    privacy:()=>{title.textContent="Privacy";sub.textContent="Informativa preliminare Beta";body.innerHTML=PRIVACY_HTML},
    account:()=>{title.textContent="Account e cloud";sub.textContent=session?"Sincronizzazione attiva":"Modalità locale";body.innerHTML=session?`<div class="sheet-row"><div><strong>${escapeHtml(session.user?.email||"Account ONE")}</strong><small>Recall e attività possono essere sincronizzati</small></div><span style="color:#79e7c7">ATTIVO</span></div><button class="primary-btn" id="sheetSync">Sincronizza adesso</button><button class="auth-mode-btn" id="sheetLogout" style="color:#ff9aaa">Esci dall'account</button>`:`<p>Puoi continuare a usare ONE senza account. Accedi solo se vuoi Recall e attività sincronizzati sul cloud.</p><button class="primary-btn" id="sheetLogin">Accedi o crea account</button>`;setTimeout(()=>{if($("sheetLogin"))$("sheetLogin").onclick=()=>{closeSheet();openAuth()};if($("sheetLogout"))$("sheetLogout").onclick=()=>logout();if($("sheetSync"))$("sheetSync").onclick=()=>{syncFromCloud();toast("Sincronizzazione avviata")}},0)},
    settings:()=>{title.textContent="Impostazioni";sub.textContent="Personalizza ONE";body.innerHTML=`<div class="sheet-row"><div><strong>Feedback aptico</strong><small>Vibrazione leggera sui comandi supportati</small></div><button class="toggle ${localStorage.one_haptics!=="off"?"on":""}" id="hapticToggle"><span></span></button></div><div class="sheet-row"><div><strong>Salva cronologia locale</strong><small>Memorizza le attività sul dispositivo</small></div><button class="toggle ${localStorage.one_history!=="off"?"on":""}" id="historyToggle"><span></span></button></div><div class="sheet-row"><div><strong>Cancella memoria locale</strong><small>Non cancella i dati cloud</small></div><button id="clearHistory" style="color:#ff8897">Cancella</button></div>`;setTimeout(bindSettings,0)},
    integrations:()=>{title.textContent="Integrazioni";sub.textContent="ONE Actions";body.innerHTML=`<div class="legal-note">ONE prepara le integrazioni. Calendario, Promemoria ed Email richiederanno autorizzazioni esplicite.</div>${["Calendario","Promemoria","Email","Mappe","File","Casa smart"].map(x=>`<div class="sheet-row"><div><strong>${x}</strong><small>Connessione non ancora attiva</small></div><span style="color:#687285;font-size:11px">PRESTO</span></div>`).join("")}`},
    actions:()=>{title.textContent="Centro azioni";sub.textContent="Azioni reali di ONE";body.innerHTML=`<div class="legal-note">ONE esegue azioni sul tuo dispositivo e chiede conferma prima di aprire app esterne.</div><div class="section-mini">PROMEMORIA</div><div id="actionReminders" class="action-list"><div class="empty-state">Caricamento…</div></div><div class="section-mini">ULTIME AZIONI</div><div id="actionHistory" class="action-list"><div class="empty-state">Caricamento…</div></div>`;setTimeout(loadActionCenter,0)},
    examples:()=>{title.textContent="Esempi pronti";sub.textContent="Dati demo nel tuo spazio";body.innerHTML=`<div class="legal-note">Scegli un pacchetto e controlla l'anteprima. I dati vengono creati solo dopo la tua conferma e restano separati per account.</div>${Object.entries(EXAMPLE_PACKS).map(([id,pack])=>`<article class="example-pack"><div class="example-pack-head"><span class="example-pack-icon">${pack.icon}</span><div class="example-pack-copy"><strong>${escapeHtml(pack.name)}</strong><small>${escapeHtml(pack.description)}</small></div></div><ul><li>1 spazio di lavoro</li><li>${pack.activities.length} attività e ${pack.issues.length} ${pack.issues.length===1?"criticità":"criticità"}</li><li>1 giornale lavori di esempio</li></ul><button class="example-install" data-example-pack="${id}">Installa esempio</button></article>`).join("")}<div id="exampleStatus" class="operation-status hidden"></div>`;setTimeout(bindExamplePacks,0)},
    about:()=>{title.textContent="ONE";sub.textContent="Versione 1.0 Site Copilot Beta";body.innerHTML=`<div style="text-align:center;padding:20px"><div class="recall-orb"><span></span></div><h3>Walk it. Say it. Done.</h3><p>ONE 1.0 trasforma un sopralluogo con voce e fotografie in un rapporto operativo verificato e tracciato.</p></div>`},
    activity:()=>{title.textContent=data.title||"Attività";sub.textContent=data.time||"";body.innerHTML=`<div class="activity-card"><span class="a-icon">${data.icon||"✦"}</span><span class="a-copy"><strong>${escapeHtml(data.title||"")}</strong><small>${escapeHtml(data.detail||"")}</small></span></div><p>${data.cloud?"Sincronizzata sul cloud ONE.":"Memorizzata sul dispositivo."}</p>`}
  };(t[type]||t.about)();$("sheet").classList.add("open");$("sheet").setAttribute("aria-hidden","false");$("scrim").classList.remove("hidden")
}
function closeSheet(){$("sheet").classList.remove("open");$("sheet").setAttribute("aria-hidden","true");if(!$("drawer").classList.contains("open"))$("scrim").classList.add("hidden")}
$("sheetClose").onclick=closeSheet;$$("[data-open]").forEach(b=>b.onclick=()=>openSheet(b.dataset.open));$("actionBtn").onclick=()=>openSheet("actions");
function bindSettings(){const ht=$("hapticToggle"),hs=$("historyToggle"),cl=$("clearHistory");if(ht)ht.onclick=()=>{ht.classList.toggle("on");localStorage.one_haptics=ht.classList.contains("on")?"on":"off";haptic()};if(hs)hs.onclick=()=>{hs.classList.toggle("on");localStorage.one_history=hs.classList.contains("on")?"on":"off";toast("Preferenza salvata")};if(cl)cl.onclick=()=>{if(confirm("Vuoi cancellare tutta la memoria locale di ONE?")){localStorage.removeItem("one_activities");renderActivities();closeSheet();toast("Memoria locale cancellata")}}}
function haptic(){if(localStorage.one_haptics!=="off"&&navigator.vibrate)navigator.vibrate(10)}document.addEventListener("click",e=>{if(e.target.closest("button"))haptic()});
$("searchInput").addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase(),a=getLocalActivities().filter(x=>(x.title+" "+x.detail).toLowerCase().includes(q));$("searchResults").innerHTML=q?(a.length?a.map(x=>`<button class="activity-card" data-activity="${x.id}"><span class="a-icon">${x.icon}</span><span class="a-copy"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.detail)}</small></span><time>${escapeHtml(x.time)}</time></button>`).join(""):`<div class="empty-state">Nessun risultato per “${escapeHtml(q)}”.</div>`):`<div class="empty-state">Inizia a scrivere per cercare.</div>`;bindActivityClicks()});

function initLegal(){const accepted=localStorage.getItem("one_legal_version")===LEGAL_VERSION;$("legalGate").classList.toggle("hidden",accepted);$("legalCheck").onchange=e=>$("acceptLegal").disabled=!e.target.checked;$("acceptLegal").onclick=()=>{localStorage.setItem("one_legal_version",LEGAL_VERSION);$("legalGate").classList.add("hidden");toast("Benvenuto in ONE")};$("gateTerms").onclick=()=>openSheet("terms");$("gatePrivacy").onclick=()=>openSheet("privacy")}

function updateAccountUI(){
  const logged=!!session, email=session?.user?.email||"";
  $("profileName").textContent=logged?(email.split("@")[0]||"Utente ONE"):"Andrea";
  $("profileStatus").textContent=logged?`Cloud attivo · ${email}`:"Modalità locale · Beta";
  $("accountTitle").textContent=logged?"Cloud ONE attivo":"Sincronizza ONE";
  $("accountSubtitle").textContent=logged?"Recall e attività sono collegati al tuo account.":"Accedi per avere Recall e attività sul cloud.";
  $("accountBtn").textContent=logged?"Gestisci":"Accedi";
  $("recallCloudState").textContent=logged?"● Cloud attivo":"○ Solo dispositivo";$("recallCloudState").classList.toggle("online",logged);
  if(logged)syncFromCloud();if($("spacesView")?.classList.contains("active-view"))loadWorkspaces();loadToday()
}
function openAuth(mode="login"){authMode=mode;$("authModal").classList.remove("hidden");$("authMessage").classList.add("hidden");updateAuthMode();setTimeout(()=>$("authEmail").focus(),200)}
function closeAuth(){$("authModal").classList.add("hidden")}
function updateAuthMode(){const signup=authMode==="signup";$("authTitle").textContent=signup?"Crea account ONE":"Accedi a ONE";$("authLead").textContent=signup?"Attiva Recall e cronologia cloud.":"Sincronizza Recall e attività in modo privato.";$("authSubmit").textContent=signup?"Crea account":"Accedi";$("authModeBtn").textContent=signup?"Hai già un account? Accedi":"Non hai un account? Crealo"}
function authMessage(msg,error=false){const e=$("authMessage");e.textContent=msg;e.classList.toggle("error",error);e.classList.remove("hidden")}
async function authFetch(path,body){
  const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:"POST",headers:{"apikey":SUPABASE_ANON_KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.message||d?.error_description||`Errore ${r.status}`);return d
}
$("authForm").onsubmit=async e=>{e.preventDefault();const email=$("authEmail").value.trim(),password=$("authPassword").value;authMessage("Connessione…");$("authSubmit").disabled=true;try{
  if(authMode==="signup"){const d=await authFetch("signup",{email,password});if(d.access_token){d.expires_at=Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d);closeAuth();toast("Account ONE creato")}else{authMessage("Account creato. Controlla l'email per confermare l'indirizzo, poi accedi.")}}
  else{const d=await authFetch("token?grant_type=password",{email,password});d.expires_at=Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d);closeAuth();toast("Accesso effettuato");await syncFromCloud()}
}catch(err){authMessage(err.message||"Accesso non riuscito",true)}finally{$("authSubmit").disabled=false}};
$("authModeBtn").onclick=()=>{authMode=authMode==="login"?"signup":"login";updateAuthMode();$("authMessage").classList.add("hidden")};$("authClose").onclick=closeAuth;$("accountBtn").onclick=()=>session?openSheet("account"):openAuth();
$("authResetBtn").onclick=async()=>{const email=$("authEmail").value.trim();if(!email){authMessage("Inserisci prima l'email del tuo account.",true);return}authMessage("Invio del link di recupero…");try{await authFetch("recover",{email});authMessage("Controlla la tua email: ti abbiamo inviato il link per impostare una nuova password.")}catch(err){authMessage(err.message||"Invio non riuscito",true)}};
function logout(){saveSession(null);sitesCache=[];selectedSiteId=null;closeSheet();renderActivities();navigate("home");toast("Sei uscito da ONE")}

function bindExamplePacks(){$$("[data-example-pack]").forEach(button=>button.onclick=()=>installExamplePack(button.dataset.examplePack,button))}
function dueDateFromNow(days){return new Date(Date.now()+days*86400000).toISOString()}
async function installExamplePack(packId,button){const pack=EXAMPLE_PACKS[packId],status=$("exampleStatus");if(!pack)return;if(!session){closeSheet();openAuth();toast("Accedi per installare un esempio");return}if(!confirm(`Installare “${pack.name}” nel tuo spazio ONE?\n\nVerranno creati un cantiere demo e i relativi dati. Potrai eliminarli in seguito.`))return;let createdSiteId=null;button.disabled=true;status.classList.remove("hidden","error");status.textContent="Installazione dell'esempio…";try{const stamp=Date.now().toString().slice(-6),owner=userId(),rows=await cloudRequest("sites",{method:"POST",body:{job_number:`DEMO-${packId.toUpperCase().slice(0,3)}-${stamp}`,name:pack.site.name,client:pack.site.client,address:pack.site.address,status:"Attivo",progress:pack.site.progress,notes:pack.site.notes,created_by:owner}}),site=rows?.[0];if(!site?.id)throw new Error("Il cantiere demo non è stato creato");createdSiteId=site.id;await Promise.all([cloudRequest("activities",{method:"POST",body:pack.activities.map(item=>({...item,site_id:site.id,created_by:owner}))}),cloudRequest("issues",{method:"POST",body:pack.issues.map(item=>({site_id:site.id,title:item.title,details:item.details,priority:item.priority,status:"Aperto",due_at:dueDateFromNow(item.dueDays),created_by:owner}))}),cloudRequest("daily_reports",{method:"POST",body:{...pack.report,site_id:site.id,report_date:localDateKey(),created_by:owner}})]);sitesCache=[];await loadWorkspaces();await loadToday();await addActivity(`${pack.name} installato`,site.name,"✦","example_pack",{pack:packId,site_id:site.id});const body=$("sheetBody");body.innerHTML=`<div class="example-success"><span class="example-pack-icon">✓</span><h3>Esempio installato</h3><p>${escapeHtml(site.name)} è pronto con attività, criticità e giornale lavori.</p><button class="primary-btn" id="openInstalledExample">Apri il cantiere demo</button></div>`;$("openInstalledExample").onclick=()=>{closeSheet();openSite(site.id)}}catch(error){if(createdSiteId)try{await cloudRequest(`sites?id=eq.${encodeURIComponent(createdSiteId)}`,{method:"DELETE"})}catch{}status.textContent=error?.message||"Installazione non riuscita";status.classList.add("error");button.disabled=false}}


function workspaceActionTitle(kind){return({create_issue:"Nuovo problema",create_activity:"Registra attività",create_daily_report:"Report giornaliero",update_site_progress:"Aggiorna avanzamento"})[kind]||"Operazione cantiere"}
async function ensureSitesCache(){if(sitesCache.length)return sitesCache;const rows=await cloudRequest("sites?select=id,job_number,name,client,address,status,progress,updated_at&order=updated_at.desc");sitesCache=Array.isArray(rows)?rows:[];return sitesCache}
function dateTimeLocalValue(value){if(!value)return"";const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value).slice(0,16);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function operationFields(action,siteId){const p=action.payload||{},siteOptions=sitesCache.map(site=>`<option value="${site.id}" ${site.id===siteId?"selected":""}>${escapeHtml(site.job_number)} · ${escapeHtml(site.name)}</option>`).join(""),site=`<label>Cantiere<select name="site_id" required><option value="">Seleziona il cantiere</option>${siteOptions}</select></label>`;
  if(action.kind==="create_issue")return site+`<label>Titolo<input name="title" maxlength="180" required value="${escapeHtml(p.title||p.text||"")}"></label><label>Descrizione<textarea name="details" maxlength="1600">${escapeHtml(p.details||p.note||p.body||"")}</textarea></label><div class="operation-grid"><label>Priorità<select name="priority"><option ${p.priority==="Bassa"?"selected":""}>Bassa</option><option ${p.priority==="Media"||!p.priority?"selected":""}>Media</option><option ${p.priority==="Alta"?"selected":""}>Alta</option><option ${p.priority==="Critica"?"selected":""}>Critica</option></select></label><label>Scadenza<input name="due_at" type="datetime-local" value="${dateTimeLocalValue(p.due_at||p.date)}"></label></div>`;
  if(action.kind==="create_activity")return site+`<label>Attività<input name="title" maxlength="180" required value="${escapeHtml(p.title||p.text||"")}"></label><label>Note<textarea name="notes" maxlength="1600">${escapeHtml(p.note||p.details||p.body||"")}</textarea></label>`;
  if(action.kind==="create_daily_report")return site+`<label>Data<input name="report_date" type="date" required value="${escapeHtml(p.report_date||p.date||localDateKey())}"></label><label>Riepilogo<input name="summary" maxlength="500" value="${escapeHtml(p.summary||p.title||"")}"></label><label>Lavorazioni<textarea name="works" maxlength="2400">${escapeHtml(p.works||p.text||"")}</textarea></label><label>Blocchi e criticità<textarea name="blockers" maxlength="1600">${escapeHtml(p.blockers||p.details||"")}</textarea></label><div class="operation-grid"><label>Persone<input name="workers" type="number" min="0" step="1" value="${escapeHtml(p.workers??"")}"></label><label>Ore<input name="hours" type="number" min="0" step="0.5" value="${escapeHtml(p.hours??"")}"></label></div>`;
  return site+`<label>Avanzamento<input name="progress" type="number" min="0" max="100" step="1" required value="${escapeHtml(p.progress??sitesCache.find(site=>site.id===siteId)?.progress??0)}"></label>`}
async function saveWorkspaceOperation(kind,data){const siteId=String(data.site_id||"");if(!siteId||!sitesCache.some(site=>site.id===siteId))throw new Error("Seleziona un cantiere accessibile");let label="";
  if(kind==="create_issue"){label=String(data.title||"").trim();if(!label)throw new Error("Inserisci il titolo del problema");await cloudRequest("issues",{method:"POST",body:{site_id:siteId,title:label,details:String(data.details||"").trim()||null,priority:String(data.priority||"Media"),status:"Aperto",due_at:data.due_at?new Date(data.due_at).toISOString():null,created_by:userId()}})}
  else if(kind==="create_activity"){label=String(data.title||"").trim();if(!label)throw new Error("Inserisci l'attività");await cloudRequest("activities",{method:"POST",body:{site_id:siteId,title:label,notes:String(data.notes||"").trim()||null,created_by:userId()}})}
  else if(kind==="create_daily_report"){label=`Report ${data.report_date||localDateKey()}`;await cloudRequest("daily_reports",{method:"POST",body:{site_id:siteId,report_date:data.report_date||localDateKey(),summary:String(data.summary||"").trim()||null,works:String(data.works||"").trim()||null,blockers:String(data.blockers||"").trim()||null,workers:data.workers===""?0:Number(data.workers),hours:data.hours===""?0:Number(data.hours),created_by:userId()}})}
  else if(kind==="update_site_progress"){const progress=progressValue(data.progress);label=`Avanzamento ${progress}%`;await cloudRequest(`sites?id=eq.${encodeURIComponent(siteId)}`,{method:"PATCH",body:{progress,updated_at:new Date().toISOString()}});const cached=sitesCache.find(site=>site.id===siteId);if(cached)cached.progress=progress}
  else throw new Error("Operazione non supportata");
  await logAction({kind,label,payload:{...data,site_id:siteId}},"executed");await addActivity(label,siteName(siteId),"✓","workspace_action",{kind,site_id:siteId});await loadToday();if(selectedSiteId===siteId)await openSite(siteId);return label}
async function openOperationReview(action,context={}){const a=normalizeAction(action);if(!session){openAuth();toast("Accedi per salvare operazioni nel cantiere");return}try{await ensureSitesCache()}catch{toast("Non riesco a caricare i cantieri");return}if(!sitesCache.length){toast("Non ci sono cantieri accessibili");return}const p=a.payload||{};let siteId=selectedSiteId||p.site_id||"";if(!sitesCache.some(site=>site.id===siteId)&&p.site_job_number)siteId=sitesCache.find(site=>String(site.job_number).toLowerCase()===String(p.site_job_number).toLowerCase())?.id||"";const title=$("sheetTitle"),sub=$("sheetSubtitle"),body=$("sheetBody");closeDrawer();title.textContent=workspaceActionTitle(a.kind);sub.textContent="Controlla i dati prima del salvataggio";body.innerHTML=`<div class="operation-summary">${escapeHtml(context?.summary||"ONE ha preparato un'operazione. Nulla verrà salvato finché non confermi.")}</div><form id="operationForm" class="operation-form">${operationFields(a,siteId)}<div id="operationStatus" class="operation-status hidden"></div><button class="primary-btn" type="submit">Conferma e salva</button><button class="operation-cancel" id="operationCancel" type="button">Annulla</button></form>`;$("sheet").classList.add("open");$("sheet").setAttribute("aria-hidden","false");$("scrim").classList.remove("hidden");$("operationCancel").onclick=closeSheet;$("operationForm").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,status=$("operationStatus"),submit=form.querySelector('[type="submit"]'),data=Object.fromEntries(new FormData(form).entries());status.classList.remove("hidden","error");status.textContent="Salvataggio nel cantiere…";submit.disabled=true;try{const saved=await saveWorkspaceOperation(a.kind,data);status.textContent=`✓ ${saved} salvato`;setTimeout(()=>{closeSheet();toast("Operazione salvata nel cantiere")},650)}catch(error){status.textContent=error?.message||"Operazione non riuscita";status.classList.add("error");submit.disabled=false}}}

function actionIcon(k){return({reminder:"◷",calendar:"▣",email:"✉",call:"☎",maps:"⌖",share:"↗",copy:"⧉",download:"⇩",search:"⌕",open_url:"↗",sms:"◌",whatsapp:"◉",save:"⌁",create_issue:"!",create_activity:"✓",create_daily_report:"▤",update_site_progress:"%"})[k]||"⚡"}
function normalizeAction(a={}){return{kind:(a.kind||a.type||"other").toLowerCase(),label:a.label||a.kind||"Azione",payload:a.payload||{},id:a.id||null}}
function actionDescription(a){const p=a.payload||{};return({reminder:p.title||p.text||"Crea promemoria ONE",calendar:p.title||p.event||"Aggiungi evento al calendario",email:p.to?`Email a ${p.to}`:"Prepara email",call:p.phone?`Chiama ${p.phone}`:"Avvia chiamata",maps:p.address||p.query||"Apri Mappe",share:"Apri Condividi di iOS",copy:"Copia negli appunti",search:p.query||"Cerca sul web",open_url:p.url||"Apri collegamento",sms:p.phone?`Messaggio a ${p.phone}`:"Apri Messaggi",whatsapp:p.phone?`WhatsApp a ${p.phone}`:"Apri WhatsApp"})[a.kind]||a.label}
function confirmAndExecuteAction(action,context={}){const a=normalizeAction(action);if(WORKSPACE_ACTION_KINDS.has(a.kind)){openOperationReview(a,context);return}if(["email","call","maps","calendar","open_url","sms","whatsapp","search"].includes(a.kind)&&!confirm(`${a.label}\n\n${actionDescription(a)}\n\nVuoi continuare?`)){logAction(a,"cancelled");return}executeAction(a,context)}
async function logAction(a,status="executed"){if(!session)return;try{await cloudRequest("one_actions",{method:"POST",body:{user_id:userId(),site_id:selectedSiteId||null,kind:a.kind,label:a.label,status,payload:a.payload||{},executed_at:status==="executed"?new Date().toISOString():null}})}catch{}}
function icsEsc(x=""){return String(x).replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function icsDate(v){const d=v?new Date(v):new Date();return (Number.isNaN(d.getTime())?new Date():d).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z/,"Z")}
function createCalendarFile(p={}){const start=p.start||p.start_at||p.date||new Date(Date.now()+3600000).toISOString(),sd=new Date(start),end=p.end||p.end_at||new Date(sd.getTime()+3600000).toISOString(),ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ONE//Action Engine//IT\r\nBEGIN:VEVENT\r\nUID:one-${Date.now()}@one\r\nDTSTAMP:${icsDate(new Date())}\r\nDTSTART:${icsDate(start)}\r\nDTEND:${icsDate(end)}\r\nSUMMARY:${icsEsc(p.title||p.event||"Evento ONE")}\r\nDESCRIPTION:${icsEsc(p.notes||p.description||"Creato con ONE")}\r\nLOCATION:${icsEsc(p.location||p.address||"")}\r\nEND:VEVENT\r\nEND:VCALENDAR`,blob=new Blob([ics],{type:"text/calendar;charset=utf-8"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=p.filename||"evento-one.ics";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000)}
async function createReminder(p={}){const title=p.title||p.text||"Promemoria ONE",note=p.note||p.notes||"",due=p.due_at||p.date||p.datetime||null,l=JSON.parse(localStorage.getItem("one_reminders")||"[]"),item={id:`local-${Date.now()}`,title,note,due_at:due,completed:false,created_at:new Date().toISOString()};l.unshift(item);localStorage.setItem("one_reminders",JSON.stringify(l.slice(0,50)));if(session)try{const r=await cloudRequest("one_reminders",{method:"POST",body:{user_id:userId(),site_id:selectedSiteId||null,title,note,due_at:due||null,completed:false,source:p}});if(r?.[0]){l[0]={...item,id:r[0].id};localStorage.setItem("one_reminders",JSON.stringify(l.slice(0,50)))}}catch{}toast("Promemoria creato in ONE");addActivity(title,due?`Promemoria · ${new Date(due).toLocaleString("it-IT")}`:"Promemoria ONE","◷","reminder")}
async function executeAction(action,context={}){const a=normalizeAction(action),p=a.payload||{};try{switch(a.kind){
case"reminder":await createReminder(p);break;
case"calendar":createCalendarFile(p);toast("Evento pronto per Calendario");break;
case"email":location.href=`mailto:${encodeURIComponent(p.to||p.email||"")}?subject=${encodeURIComponent(p.subject||context?.summary||"")}&body=${encodeURIComponent(p.body||p.text||context?.summary||"")}`;break;
case"call":location.href=`tel:${String(p.phone||p.number||"").replace(/[^\d+]/g,"")}`;break;
case"sms":{const ph=String(p.phone||"").replace(/[^\d+]/g,""),tx=p.text||p.body||context?.summary||"";location.href=`sms:${ph}${tx?`&body=${encodeURIComponent(tx)}`:""}`;break}
case"whatsapp":window.open(`https://wa.me/${String(p.phone||"").replace(/[^\d]/g,"")}?text=${encodeURIComponent(p.text||p.body||context?.summary||"")}`,"_blank","noopener");break;
case"maps":window.open(`https://maps.apple.com/?q=${encodeURIComponent(p.address||p.query||p.location||context?.summary||"")}`,"_blank","noopener");break;
case"search":window.open(`https://www.google.com/search?q=${encodeURIComponent(p.query||p.text||context?.summary||"")}`,"_blank","noopener");break;
case"open_url":if(!(p.url||p.href))throw Error("URL mancante");window.open(p.url||p.href,"_blank","noopener");break;
case"copy":await navigator.clipboard.writeText(p.text||p.content||context?.summary||"");toast("Copiato negli appunti");break;
case"share":{const d={title:p.title||"ONE",text:p.text||context?.summary||"",url:p.url||undefined};if(navigator.share)await navigator.share(d);else{await navigator.clipboard.writeText([d.text,d.url].filter(Boolean).join("\n"));toast("Contenuto copiato")};break}
case"download":{const b=new Blob([p.content||p.text||context?.summary||""],{type:p.mime||"text/plain;charset=utf-8"}),u=URL.createObjectURL(b),ln=document.createElement("a");ln.href=u;ln.download=p.filename||"one.txt";document.body.appendChild(ln);ln.click();ln.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);break}
case"save":await saveMemory(context,"action","");break;
default:toast("Questa azione richiede ancora un'integrazione dedicata");await logAction(a,"unsupported");return}
await logAction(a,"executed");addActivity(a.label,actionDescription(a),actionIcon(a.kind),"action",p)}catch(e){toast("Azione non completata");await logAction(a,"failed")}}
async function getReminders(){if(session)try{const r=await cloudRequest("one_reminders?select=*&order=created_at.desc&limit=20");localStorage.setItem("one_reminders",JSON.stringify(r));return r}catch{}try{return JSON.parse(localStorage.getItem("one_reminders")||"[]")}catch{return[]}}
async function toggleReminder(id,completed){let l=await getReminders(),x=l.find(v=>v.id===id);if(!x)return;x.completed=completed;localStorage.setItem("one_reminders",JSON.stringify(l));if(session&&!String(id).startsWith("local-"))try{await cloudRequest(`one_reminders?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:{completed,updated_at:new Date().toISOString()}})}catch{}await loadActionCenter()}
async function loadActionCenter(){const re=$("actionReminders"),hi=$("actionHistory");if(!re||!hi)return;const r=await getReminders();re.innerHTML=r.length?r.slice(0,10).map(x=>`<div class="reminder-item ${x.completed?"done":""}"><button class="reminder-check" data-reminder="${x.id}" data-completed="${x.completed?"1":"0"}">${x.completed?"✓":""}</button><div class="reminder-copy"><strong>${escapeHtml(x.title)}</strong><small>${x.due_at?escapeHtml(new Date(x.due_at).toLocaleString("it-IT")):"Senza scadenza"}${x.note?" · "+escapeHtml(x.note):""}</small></div></div>`).join(""):`<div class="empty-state">Nessun promemoria ONE.</div>`;$$("[data-reminder]").forEach(b=>b.onclick=()=>toggleReminder(b.dataset.reminder,b.dataset.completed!=="1"));if(session)try{const rows=await cloudRequest("one_actions?select=*&order=created_at.desc&limit=15");hi.innerHTML=rows.length?rows.map(x=>`<div class="action-item"><div class="ai">${actionIcon(x.kind)}</div><div class="ac"><strong>${escapeHtml(x.label)}</strong><small>${escapeHtml(x.kind)}</small></div><span class="status">${escapeHtml(x.status)}</span></div>`).join(""):`<div class="empty-state">Nessuna azione eseguita.</div>`}catch{hi.innerHTML=`<div class="empty-state">Storico cloud non disponibile.</div>`}else hi.innerHTML=`<div class="empty-state">Accedi a ONE per sincronizzare lo storico delle azioni.</div>`}

if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=10").catch(()=>{}))}
renderActivities();$("searchResults").innerHTML=`<div class="empty-state">Inizia a scrivere per cercare.</div>`;setState("idle");initLegal();updateSend();updateAccountUI();
